// vue3-vite/src/view/demo4/Button/Loading.tsx
import { defineComponent, render, renderSlot } from "vue"
import "./Loading.css"
const ButtonCom = defineComponent({
    setup(props, { emit, slots }) {
        return () => (
            <div class="loading">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        )
    },
})
export default ButtonCom

// react/react-admin-master/src/components/demoCom/Loading.tsx
import React from 'react';
import './Loading.css';
function ButtonCom() {
    <div className="loading">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>;
}
export default ButtonCom;
